// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SyntacticVersioning")>]
[<assembly: AssemblyProductAttribute("SyntacticVersioning")>]
[<assembly: AssemblyDescriptionAttribute("Syntactic (Semantic) Versioning for .NET libraries heavily inspired in elm-package (bump and diff)")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SyntacticVersioning"
    let [<Literal>] AssemblyProduct = "SyntacticVersioning"
    let [<Literal>] AssemblyDescription = "Syntactic (Semantic) Versioning for .NET libraries heavily inspired in elm-package (bump and diff)"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
