// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SynVer.FAKE")>]
[<assembly: AssemblyProductAttribute("SynVer")>]
[<assembly: AssemblyDescriptionAttribute("Syntactic (Semantic) Versioning for .NET libraries heavily inspired in elm-package (bump and diff)")>]
[<assembly: AssemblyVersionAttribute("0.0.6")>]
[<assembly: AssemblyFileVersionAttribute("0.0.6")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SynVer.FAKE"
    let [<Literal>] AssemblyProduct = "SynVer"
    let [<Literal>] AssemblyDescription = "Syntactic (Semantic) Versioning for .NET libraries heavily inspired in elm-package (bump and diff)"
    let [<Literal>] AssemblyVersion = "0.0.6"
    let [<Literal>] AssemblyFileVersion = "0.0.6"
    let [<Literal>] AssemblyConfiguration = "Release"
